package app.model;
// Generated Feb 21, 2019 7:34:52 PM by Hibernate Tools 3.5.0.Final

import java.util.List;

/**
 * Categories generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer id;
	private String categoryName;
	private int parentId;
	private String metaLink;
	private int displayNo;
	private String iconImg;
	private String avatar;
	private String description;
	private boolean showHome;
	private Boolean status;
	private List<News> newses;
	private List<Product> products;

	public Category() {
	}

	public Category(String categoryName, int parentId, String metaLink, int displayNo, boolean showHome) {
		this.categoryName = categoryName;
		this.parentId = parentId;
		this.metaLink = metaLink;
		this.displayNo = displayNo;
		this.showHome = showHome;
	}
	
	public Category(Integer id, String categoryName, int parentId, String metaLink, int displayNo, String iconImg,
			String avatar, String description, boolean showHome, Boolean status, List<News> newses,
			List<Product> products) {
		super();
		this.id = id;
		this.categoryName = categoryName;
		this.parentId = parentId;
		this.metaLink = metaLink;
		this.displayNo = displayNo;
		this.iconImg = iconImg;
		this.avatar = avatar;
		this.description = description;
		this.showHome = showHome;
		this.status = status;
		this.newses = newses;
		this.products = products;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	public String getMetaLink() {
		return this.metaLink;
	}

	public void setMetaLink(String metaLink) {
		this.metaLink = metaLink;
	}

	public int getDisplayNo() {
		return this.displayNo;
	}

	public void setDisplayNo(int displayNo) {
		this.displayNo = displayNo;
	}

	public String getIconImg() {
		return this.iconImg;
	}

	public void setIconImg(String iconImg) {
		this.iconImg = iconImg;
	}

	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isShowHome() {
		return this.showHome;
	}

	public void setShowHome(boolean showHome) {
		this.showHome = showHome;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public List<News> getNewses() {
		return newses;
	}

	public void setNewses(List<News> newses) {
		this.newses = newses;
	}

	public List<Product> getProducts() {
		return products;
	}

	public void setProducts(List<Product> products) {
		this.products = products;
	}
	
}
