package app.model;
// Generated Feb 21, 2019 7:34:52 PM by Hibernate Tools 3.5.0.Final

import java.util.List;
/**
 * Customers generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer id;
	private String fullName;
	private String email;
	private String phone;
	private String address;
	private Boolean status;
	private List<Order> orderses;

	public Customer() {
	}

	public Customer(String fullName, String email) {
		this.fullName = fullName;
		this.email = email;
	}

	public Customer(Integer id, String fullName, String email, String phone, String address, Boolean status,
			List<Order> orderses) {
		super();
		this.id = id;
		this.fullName = fullName;
		this.email = email;
		this.phone = phone;
		this.address = address;
		this.status = status;
		this.orderses = orderses;
	}

	public List<Order> getOrderses() {
		return orderses;
	}

	public void setOrderses(List<Order> orderses) {
		this.orderses = orderses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public List<Order> getLstOrder() {
		return orderses;
	}

	public void setLstOrder(List<Order> orderses) {
		this.orderses = orderses;
	}

	

}
