package app.model;
// Generated Feb 21, 2019 9:18:27 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String postTitle;
	private String postContent;
	private String author;
	private String description;
	private String featureImg;
	private Date createDate;
	private Boolean status;

	public News() {
	}

	public News(Category categories, String postTitle, String postContent, String author) {
		this.category = categories;
		this.postTitle = postTitle;
		this.postContent = postContent;
		this.author = author;
	}

	public News(Category category, String postTitle, String postContent, String author, String description,
			String featureImg, Date createDate, Boolean status) {
		this.category = category;
		this.postTitle = postTitle;
		this.postContent = postContent;
		this.author = author;
		this.description = description;
		this.featureImg = featureImg;
		this.createDate = createDate;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}
	
	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategories() {
		return this.category;
	}

	public void setCategories(Category categories) {
		this.category = categories;
	}

	public String getPostTitle() {
		return this.postTitle;
	}

	public void setPostTitle(String postTitle) {
		this.postTitle = postTitle;
	}

	public String getPostContent() {
		return this.postContent;
	}

	public void setPostContent(String postContent) {
		this.postContent = postContent;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getFeatureImg() {
		return this.featureImg;
	}

	public void setFeatureImg(String featureImg) {
		this.featureImg = featureImg;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
