package app.model;
// Generated Feb 21, 2019 7:34:52 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.List;

/**
 * Orders generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer id;
	private Customer customers;
	private User users;
	private String address;
	private Float total;
	private Date createDate;
	private Boolean status;
	private List<OrderDetail> orderDetails;

	public Order() {
	}
	
	public List<OrderDetail> getLstOrderDetail() {
		return orderDetails;
	}

	public void setLstOrderDetail(List<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

	public Order(Customer customers, User users) {
		this.customers = customers;
		this.users = users;
	}

	public Order(Integer id, Customer customers, User users, String address, Float total, Date createDate,
			Boolean status, List<OrderDetail> orderDetails) {
		super();
		this.id = id;
		this.customers = customers;
		this.users = users;
		this.address = address;
		this.total = total;
		this.createDate = createDate;
		this.status = status;
		this.orderDetails = orderDetails;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Customer getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customer customers) {
		this.customers = customers;
	}

	public User getUsers() {
		return this.users;
	}

	public void setUsers(User users) {
		this.users = users;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Float getTotal() {
		return this.total;
	}

	public void setTotal(Float total) {
		this.total = total;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public List<OrderDetail> getOrderDetails() {
		return orderDetails;
	}

	public void setOrderDetails(List<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}
	
}
