package app.model;
// Generated Feb 21, 2019 7:34:52 PM by Hibernate Tools 3.5.0.Final

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetail implements java.io.Serializable {

	private Integer id;
	private Product products;
	private Order orders;
	private int quantity;
	private Float price;
	private Boolean status;

	public OrderDetail() {
	}

	public OrderDetail(Product products, Order orders, int quantity) {
		this.products = products;
		this.orders = orders;
		this.quantity = quantity;
	}

	public OrderDetail(Product products, Order orders, int quantity, Float price, Boolean status) {
		this.products = products;
		this.orders = orders;
		this.quantity = quantity;
		this.price = price;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Product getProducts() {
		return this.products;
	}

	public void setProducts(Product products) {
		this.products = products;
	}

	public Order getOrders() {
		return this.orders;
	}

	public void setOrders(Order orders) {
		this.orders = orders;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
