package app.model;
// Generated Feb 21, 2019 7:34:52 PM by Hibernate Tools 3.5.0.Final

/**
 * Sliders generated by hbm2java
 */
public class Slider implements java.io.Serializable {

	private Integer id;
	private String sliderImg;
	private int displayNo;
	private Boolean status;

	public Slider() {
	}

	public Slider(String sliderImg, int displayNo) {
		this.sliderImg = sliderImg;
		this.displayNo = displayNo;
	}

	public Slider(String sliderImg, int displayNo, Boolean status) {
		this.sliderImg = sliderImg;
		this.displayNo = displayNo;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSliderImg() {
		return this.sliderImg;
	}

	public void setSliderImg(String sliderImg) {
		this.sliderImg = sliderImg;
	}

	public int getDisplayNo() {
		return this.displayNo;
	}

	public void setDisplayNo(int displayNo) {
		this.displayNo = displayNo;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
