package app.model;
// Generated Feb 21, 2019 7:34:52 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.List;

/**
 * Users generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String fullName;
	private String email;
	private String passWord;
	private String phone;
	private String avatar;
	private String codeConfirm;
	private byte role;
	private Date createDate;
	private Boolean status;
	private List<Order> orders;

	public User() {
	}

	public User(String fullName, String email, String passWord, byte role) {
		this.fullName = fullName;
		this.email = email;
		this.passWord = passWord;
		this.role = role;
	}

	public User(Integer id, String fullName, String email, String passWord, String phone, String avatar,
			String codeConfirm, byte role, Date createDate, Boolean status, List<Order> orders) {
		super();
		this.id = id;
		this.fullName = fullName;
		this.email = email;
		this.passWord = passWord;
		this.phone = phone;
		this.avatar = avatar;
		this.codeConfirm = codeConfirm;
		this.role = role;
		this.createDate = createDate;
		this.status = status;
		this.orders = orders;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassWord() {
		return this.passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public String getCodeConfirm() {
		return this.codeConfirm;
	}

	public void setCodeConfirm(String codeConfirm) {
		this.codeConfirm = codeConfirm;
	}

	public byte getRole() {
		return this.role;
	}

	public void setRole(byte role) {
		this.role = role;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public List<Order> getOrders() {
		return orders;
	}

	public void setOrders(List<Order> orders) {
		this.orders = orders;
	}

}
